twitter-listener-service:
  event:
    queue:
      name: "tweetQueue"

  tweet-keywords:
    - news
    - latestnews
    - euronews
    - breaking news


destinations:
  topics:
    tweetQueue:
      exchange: tweetQueue
      routing-key: tweetQueue
