apiVersion: skaffold/v2beta22
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: davidjmartin/api-gateway
    context: ./api-gateway
  - image: davidjmartin/swap-rate-api
    context: ./swap-rate-api
  - image: davidjmartin/cot-report-api
    context: ./cot-report-api
  - image: davidjmartin/twitter-crawler-api
    context: ./twitter-crawler-api
  - image: davidjmartin/cot-report-frontend
    context: ./cot-report-frontend/frontendv5
deploy:
  helm:
    releases:
    - name: nginx-ingress-controller
      chartPath: ./nginx-ingress-controller
      imageStrategy:
        helm: {}
    - name: api-gateway
      chartPath: ./api-gateway/chart
      artifactOverrides:
        image: davidjmartin/api-gateway
      createNamespace: true
      imageStrategy:
        helm: {}
    - name: swap-rate-api
      chartPath: ./swap-rate-api/chart
      artifactOverrides:
        image: davidjmartin/swap-rate-api
      imageStrategy:
        helm: {}
    - name: cot-report-api
      chartPath: ./cot-report-api/chart
      artifactOverrides:
        image: davidjmartin/cot-report-api
      imageStrategy:
        helm: { }
    - name: twitter-crawler-api
      chartPath: ./twitter-crawler-api/chart
      artifactOverrides:
        image: davidjmartin/twitter-crawler-api
      imageStrategy:
        helm: {}
    - name: cot-report-frontend
      chartPath: ./cot-report-frontend/frontendv5/chart
      artifactOverrides:
        image: davidjmartin/cot-report-frontend
      imageStrategy:
        helm: {}

