server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: cot-report-api
          uri: http://cot-report-api:80
          predicates:
            - Path=/api/report**, /api/report**/*
        - id: swap-rate-api
          uri: http://swap-rate-api:80
          predicates:
            - Path=/api/swaps**, /api/swaps**/*
management:
  endpoints:
    web:
      exposure:
        include: "*"
