server:
  port: 80

twitter-crawler-service:
  twitter-keywords:
    - '$EURUSD'
    - '$AUDUSD'
    - '$GBPUSD'
    - '$NZDUSD'
    - '$AUDNZD'
    - '$XAUUSD'
    - '$USDCHF'
    - '$CADJPY'
    - '$GBPJPY'
    - '$DXY'
    - '#EURUSD'
    - '#AUDUSD'
    - '#GBPUSD'
    - '#NZDUSD'
    - '#AUDNZD'
    - '#XAUUSD'
    - '#USDCHF'
    - '#CADJPY'
    - '#GBPJPY'
    - '#DXY'




