apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass }}
{{- if .Values.controller.setAsDefaultIngress }}
  annotations:  
{{- end }}
spec:
  controller: nginx.org/ingress-controller
