apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-projectz.xyz
  namespace: default
spec:
  secretName: cot-report-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cloud-projectz.xyz
  dnsNames:
    - cloud-projectz.xyz